-- ============================================================================
-- 1. TABLAS PRINCIPALES PARA EL NEGOCIO 
-- ============================================================================

CREATE TABLE cliente (
    id_cliente NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nombre_cliente VARCHAR2(50) NOT NULL,
    apellido_cliente VARCHAR2(50) NOT NULL,
    dui_cliente VARCHAR2(10) NOT NULL,
    telefono_cliente  VARCHAR2(15),
    email_cliente VARCHAR2(100),
    CONSTRAINT pk_cliente PRIMARY KEY (id_cliente),
    CONSTRAINT uq_dui_cliente UNIQUE (dui_cliente)
);

CREATE TABLE empleado (
    id_empleado  NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nombre_empleado VARCHAR2(50) NOT NULL,
    apellido_empleado VARCHAR2(50) NOT NULL,
    telefono_empleado VARCHAR2(15),
    email_empleado VARCHAR2(100),
    CONSTRAINT pk_empleado PRIMARY KEY (id_empleado)
);

CREATE TABLE categoria (
    id_categoria NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nombre_categoria VARCHAR2(50) NOT NULL,
    precio_categoria NUMBER(10, 2) NOT NULL,
    CONSTRAINT pk_categoria PRIMARY KEY (id_categoria)
);

CREATE TABLE salon (
    id_salon NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nombre_salon VARCHAR2(50) NOT NULL,
    capacidad_max NUMBER NOT NULL,
    precio_hora NUMBER(10, 2) NOT NULL,
    CONSTRAINT pk_salon PRIMARY KEY (id_salon)
);

CREATE TABLE asistente (
    id_asistente NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nombre_asistente VARCHAR2(50) NOT NULL,
    apellido_asistente VARCHAR2(50) NOT NULL,
    telefono_asistente VARCHAR2(15),
    CONSTRAINT pk_asistente PRIMARY KEY (id_asistente)
);

CREATE TABLE evento (
    id_evento NUMBER GENERATED BY DEFAULT AS IDENTITY,
    id_cliente NUMBER NOT NULL,
    id_empleado NUMBER NOT NULL, 
    id_categoria NUMBER NOT NULL,
    id_salon NUMBER NOT NULL,
    nombre_evento VARCHAR2(160) NOT NULL, 
    fecha_hora_inicio DATE NOT NULL,     
    fecha_hora_fin DATE NOT NULL,
    estado VARCHAR2(20) NOT NULL,
    CONSTRAINT pk_evento PRIMARY KEY (id_evento),
    CONSTRAINT fk_evento_cliente FOREIGN KEY (id_cliente) REFERENCES cliente(id_cliente),
    CONSTRAINT fk_evento_empleado FOREIGN KEY (id_empleado) REFERENCES empleado(id_empleado),
    CONSTRAINT fk_evento_categoria FOREIGN KEY (id_categoria) REFERENCES categoria(id_categoria),
    CONSTRAINT fk_evento_salon FOREIGN KEY (id_salon) REFERENCES salon(id_salon)
);


CREATE TABLE registro_pago (
    id_pago NUMBER GENERATED BY DEFAULT AS IDENTITY,
    id_evento NUMBER NOT NULL,
    fecha_pago DATE NOT NULL, 
    monto_pagado NUMBER(10, 2) NOT NULL,
    CONSTRAINT pk_registro_pago PRIMARY KEY (id_pago),
    CONSTRAINT fk_pago_evento FOREIGN KEY (id_evento) REFERENCES evento(id_evento)
);

CREATE TABLE control_asistencia (
    id_asistente NUMBER NOT NULL,
    id_evento NUMBER NOT NULL,
    CONSTRAINT pk_control_asistencia PRIMARY KEY (id_asistente, id_evento),
    CONSTRAINT fk_asiste_asistente FOREIGN KEY (id_asistente) REFERENCES asistente(id_asistente),
    CONSTRAINT fk_asiste_evento FOREIGN KEY (id_evento) REFERENCES evento(id_evento)
);

-- ============================================================================
-- 2. AUDITORIA Y REGISTRO DE ERRORES
-- ============================================================================

CREATE TABLE auditoria_evento (
    id_auditoria NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    usuario_oracle VARCHAR2(100) DEFAULT USER,
    fecha_hora TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    accion VARCHAR2(10),           
    columna_afectada VARCHAR2(50),      
    valor_anterior VARCHAR2(4000),       
    valor_nuevo VARCHAR2(4000),     
    id_evento_afectado NUMBER
);

CREATE TABLE LOG_ERRORES (
    id_log NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre_procedimiento VARCHAR2(100),
    mensaje_error VARCHAR2(4000),
    usuario_oracle VARCHAR2(100) DEFAULT USER,
    fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);